[package]
name = "hailmary"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.64"
uuid = { version = "1.11.0", features = ["v4"] }
