//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub item_id: String,
    pub user_id: String,
    #[sea_orm(unique)]
    pub plaid_account_id: String,
    pub name: String,
    pub mask: Option<String>,
    pub official_name: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub current_balance: f64,
    #[sea_orm(column_type = "Double")]
    pub available_balance: f64,
    pub iso_currency_code: Option<String>,
    pub unofficial_currency_code: Option<String>,
    pub r#type: Option<String>,
    pub subtype: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plaid_items::Entity",
        from = "Column::ItemId",
        to = "super::plaid_items::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlaidItems,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::plaid_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaidItems.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
