// Code generated by github.com/edgedb/edgedb-go/cmd/edgeql-go DO NOT EDIT.

package main

import (
	"context"
	_ "embed"

	"github.com/edgedb/edgedb-go"
)

//go:embed GetUserOlderThanAge.edgeql
var getuserolderthanageCmd string

// getuserolderthanageResult
// is part of the return type for
// getuserolderthanage()
type getuserolderthanageResult struct {
	id   edgedb.UUID `edgedb:"id"`
	name string      `edgedb:"name"`
	age  int16       `edgedb:"age"`
}

// getuserolderthanage
// runs the query found in
// GetUserOlderThanAge.edgeql
func getuserolderthanage(
	ctx context.Context,
	client *edgedb.Client,
	age int16,
) ([]getuserolderthanageResult, error) {
	var result []getuserolderthanageResult

	err := client.Query(
		ctx,
		getuserolderthanageCmd,
		&result,
		map[string]interface{}{
			"age": age,
		},
	)

	return result, err
}

// getuserolderthanageJSON
// runs the query found in
// GetUserOlderThanAge.edgeql
// returning the results as json encoded bytes
func getuserolderthanageJSON(
	ctx context.Context,
	client *edgedb.Client,
	age int16,
) ([]byte, error) {
	var result []byte

	err := client.QueryJSON(
		ctx,
		getuserolderthanageCmd,
		&result,
		map[string]interface{}{
			"age": age,
		},
	)
	if err != nil {
		return nil, err
	}

	return result, nil
}
