[package]
name = "proxy_api"
version = "0.1.0"
edition = "2021"

[dependencies]
httpclient = "0.21.3"
plaid = "8.0.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.61"
