services:
  lavinmq:
    image: cloudamqp/lavinmq
    ports:
      - "5672:5672" # main port
      - "15672:15672" # management UI
  postgres-prod-dump:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres