//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plaid_api_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub item_id: String,
    pub user_id: String,
    pub plaid_method: String,
    pub arguments: Option<String>,
    #[sea_orm(unique)]
    pub request_id: Option<String>,
    pub error_type: Option<String>,
    pub error_code: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plaid_items::Entity",
        from = "Column::ItemId",
        to = "super::plaid_items::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlaidItems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::plaid_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaidItems.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
