//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::accounts::Entity as Accounts;
pub use super::assets::Entity as Assets;
pub use super::goals::Entity as Goals;
pub use super::plaid_api_events::Entity as PlaidApiEvents;
pub use super::plaid_items::Entity as PlaidItems;
pub use super::plaid_link_events::Entity as PlaidLinkEvents;
pub use super::transactions::Entity as Transactions;
pub use super::users::Entity as Users;
