services:
  faktory:
    image: contribsys/faktory:latest
    environment:
      FAKTORY_PROVIDER: FAKE
      FAKTORY_REDIS_URL: "redis://redis:6379"
    ports:
      - "7419:7419"
      - "7420:7420"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  redis_data:
    driver: local