name: finny
description: "Real-time retirement calculator and financial planner."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.22.1
  drift_flutter: ^0.2.2
  drift_sqlite_async: ^0.2.0
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  plaid_flutter: ^4.1.1
  provider: ^6.1.2
  powersync: ^1.10.0
  sentry_flutter: ^8.11.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.5.7
  uuid: ^4.4.2
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.11
  drift_dev: ^2.22.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
