name: finny
description: "Real-time retirement calculator and financial planner for YNAB."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  sentry_flutter: ^9.0.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.5
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  generate: true

  # todo: https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
  # synthetic-package: false
  # # The files are generated into the path specified by `arb-dir`
  # arb-dir: lib/src/localization
  # # Or, specifically provide an output path:
  # output-dir: lib/src/generated/i18n

  assets:
    - assets/
