generate:
  - types
  - client
accessModifier: public
filter:
  paths: 
    - "/link/token/create"
    - "/item/get"
    - "/item/public_token/exchange"
    - "/transactions/sync"
    - "/accounts/get"
