name: api ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scala-api
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: supabase/setup-cli@v1
      - run: supabase db start
      - name: Compile
        run: make compile
      - name: Run tests
        run: make test