name: api ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scala-api
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
      
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Start Supabase Postgres
        run: supabase db start

      - name: Compile
        run: make compile

      - name: Run tests
        run: make test